### ISSUE TITLE
Move the context generic programming crash course from hermes-sdk repo

### ISSUE THREAD

**Issue by seanchen1991** [contextgeneric/cgp#2]
Should the [context-generic-programming](https://github.com/informalsystems/hermes-sdk/blob/main/crates/relayer-all-in-one/src/docs/context_generic_programming.rs) crash course live in this repo instead of in the hermes-sdk repo?

**Comment by soareschen** [comment]
Closing this, with new learning materials available at https://patterns.contextgeneric.dev/.
